@startuml
'https://plantuml.com/class-diagram

interface SqlSession
interface Executor

SqlSession <|-- DefaultSqlSession
Executor <|-- CachingExecutor


class DefaultSqlSession {
Executor executor
clearCache() { executor.clearLocalCache(); }
}

class CachingExecutor {
Executor delegate
clearLocalCache() { delegate.clearLocalCache(); }
}

@enduml
